# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CDtz6bUwEV6p42wr6LV4SHPjivmElDL6
"""

import numpy as np
x = np.array([0.1, 0.2, 0.3])
w = np.array([[0.1,0.2],
           [0.2,0.4],
           [0.3,0.5]])
b=np.array([0.1,0.2])
z=np.dot(x,w)+b
print("output:",z)
def sigmoid(x):
    return 1/(1+np.exp(-x))
a1=sigmoid(z) # Renamed y to a1 for clarity
print("Activation output:",a1)
w2 = np.array([[0.1], [0.4]])
b2 = np.array([0.1])
z2 = np.dot(a1, w2) + b2 # Used a1 here
print("output:",z2)
y_true = 1 # Renamed y to y_true to avoid conflict
loss = (y_true - z2) ** 2
print("Loss:", loss)
lr=0.1
dloss_dz2 = -2*(y_true-z2) # Corrected NameError: a2 -> z2, y -> y_true
grad_w2 = dloss_dz2 * a1.reshape(2,1) # Used dloss_dz2 and a1 (previous layer's activation)
w2 = w2 - lr * grad_w2
print("updated w2:",w2)