# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CkDhrRFt_EVpRyDKU09lI2FQauwdI1Pl
"""

import numpy as np

class FeedForwardNN:
    def __init__(self):
        self.w1 = np.array([[0.1, 0.2],
                            [0.3, 0.5],
                            [0.5, 0.7]])
        self.b1 = np.array([0.5, 0.6])

        self.w2 = np.array([[0.2],
                            [0.3]])
        self.b2 = np.array([0.5])

        self.lr = 0.1

    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))

    def forward(self, x):
        self.z1 = np.dot(x, self.w1) + self.b1
        self.a1 = self.sigmoid(self.z1)

        self.z2 = np.dot(self.a1, self.w2) + self.b2
        self.a2 = self.sigmoid(self.z2)

        return self.a2

    def loss(self, y, y_pred):
        return (y - y_pred) ** 2

    def backward(self, y):
        dloss_da2 = -2 * (y - self.a2)
        da2_dz2 = self.a2 * (1 - self.a2)

        grad_w2 = dloss_da2 * da2_dz2 * self.a1
        grad_b2 = dloss_da2 * da2_dz2

        self.w2 -= self.lr * grad_w2.reshape(2, 1)
        self.b2 -= self.lr * grad_b2

    def train(self, x, y):
        y_pred = self.forward(x)
        loss = self.loss(y, y_pred)
        self.backward(y)
        return y_pred, loss


# -------- Execution --------
x = np.array([0.1, 0.2, 0.3])
y = 1

model = FeedForwardNN()
output, loss = model.train(x, y)

print("Final Output:", output)
print("Loss:", loss)
print("Updated w2:", model.w2)
print("Updated b2:", model.b2)