# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BvLqbWLQ_K1-lktgZ4qFki7GiVu4k446
"""

import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

x=np.array([[0,0], [0,2],[1,1],[1,2]])
y=np.array([[0],[1],[1],[0]])

model = Sequential()
model.add(Dense(16, input_dim=2, activation='sigmoid'))
model.add(Dense(1,activation ='sigmoid'))

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

# Train the model
model.fit(x, y, epochs=100, verbose=0)

# Evaluate the model
loss, accuracy = model.evaluate(x, y)
print("Loss:", loss)
print("Accuracy:", accuracy)

# Predictions
predictions = model.predict(x)
print("\nPredictions:")
print(predictions.round())